# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS
    env:
      SHA8: ${GITHUB_SHA::8}

    strategy:
      matrix:
        deno: ["nightly"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Compile denat
        run: |
          mkdir out
          deno compile --allow-net --unstable --allow-read --allow-write -o out/denat index.ts
     
      - name: Compress denat
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: out
          files: |
            .
          outPath: denat-${{ matrix.os }}.tar.gz
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: denat-${{ matrix.os }}.tar.gz
          asset_name: denat-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: "denat"
        

